- name: intel-cpupower is installed
  ansible.builtin.apt:
    name: linux-cpupower

- name: cpu-governor service is installed
  ansible.builtin.template:
    src: templates/cpu-governor.service.j2
    dest: /etc/systemd/system/cpu-governor.service
    owner: root
    group: root
    mode: "644"
  notify: restart cpu-governor service

- name: cpu-governor service is enabled and running
  ansible.builtin.systemd:
    name: cpu-governor.service
    enabled: yes
    state: started
    daemon_reload: yes
