#!/usr/bin/env bash

# Perform integration tests on the modules
# To keep retrying a failing test, you can set the following environment variables.
# This is mainly intended for CI use.
#   TEST_RETRIES=<num> - Number of times to try the test. Default: 1
#   TEST_RETRY_DELAY=<num> - Number of seconds to wait between failing test runs. Default: 300 (5min)

set -eu
set -o pipefail

SCRIPT_DIRECTORY=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# shellcheck disable=1091
source "$SCRIPT_DIRECTORY/constants.sh"
# shellcheck disable=1091
source "$SCRIPT_DIRECTORY/util.sh"

TEST_RETRIES="${TEST_RETRIES:-1}"
TEST_RETRY_DELAY="${TEST_RETRY_DELAY:-300}"

# Docker settings
export PROXMOX_PODMAN_NETWORK="proxmox-ansible-modules"

# Cleanup function to delete any docker objects that we might have created
cleanup() {
    echo "Cleaning up..."
    set +e # cleanup, we don't care if some stuff doesn't exist
    podman network rm "$PROXMOX_PODMAN_NETWORK" > /dev/null
    echo "Done"
    set -e
    exit
}
trap cleanup INT ERR EXIT

prepare() {
    podman network create $PROXMOX_PODMAN_NETWORK
}

run() {
    retry "$TEST_RETRIES" "$TEST_RETRY_DELAY" tox -e integration -- \
        --color -v \
        --controller docker:default --target "docker:default,python=$PYTHON_VERSION" \
        --docker-network $PROXMOX_PODMAN_NETWORK  \
        --docker-terminate=always #Change this if you want to debug test targets
}

main() {
    # shellcheck disable=1091
    source "$SCRIPT_DIRECTORY/constants.sh"

    prepare
    run
    cleanup
}

main "$@"
