- name: Remove key from trusted.gpg.d if present
  ansible.builtin.file:
    # the old version of this role only ever installed the bullseye key, so thats the only one we need to remove.
    path: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    state: absent

- name: Determine repository suite
  ansible.builtin.set_fact:
    # Non-debian distributions only get the static binary so the exact suite does not matter
    _pbs_client_apt_suite: "{{ (ansible_distribution == 'Debian') | ternary(ansible_distribution_release, 'trixie') }}"

- name: old list-style repository is absent
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/download_proxmox_com_debian_pbs_client.list
    state: absent

- name: python3-debian is installed
  ansible.builtin.apt:
    name: python3-debian

- name: deb822-style repository is present
  ansible.builtin.deb822_repository:
    name: pbs-client
    types: deb
    uris: http://download.proxmox.com/debian/pbs-client
    suites: "{{ _pbs_client_apt_suite }}"
    components: main
    signed_by: https://enterprise.proxmox.com/debian/proxmox-release-{{ _pbs_client_apt_suite }}.gpg

- name: Proxmox Backup Client is installed
  ansible.builtin.apt:
    name: proxmox-backup-client
    update_cache: true
  when: ansible_distribution == "Debian"
- name: Proxmox Backup Client (static) is installed
  ansible.builtin.apt:
    name: proxmox-backup-client-static
    update_cache: true
  when: ansible_distribution != "Debian"
